# Generated by Django 4.2.1 on 2023-06-09 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_class', models.CharField(default='', max_length=50)),
                ('link', models.URLField()),
                ('year', models.IntegerField(default=1)),
                ('semester', models.CharField(default='1', max_length=5)),
                ('ects', models.IntegerField(default=1)),
                ('ranking', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio.article')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('news_link', models.URLField()),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('course_class', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('linkedin', models.URLField()),
                ('other_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TechAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parts', models.ManyToManyField(related_name='Tech_Authors', to='portfolio.part')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('logo', models.ImageField(upload_to='portfolio/images/')),
                ('part', models.CharField(default='', max_length=10)),
                ('website_link', models.URLField()),
                ('description', models.CharField(default='', max_length=500)),
                ('authors', models.ManyToManyField(related_name='Tech_Authors', to='portfolio.techauthor')),
            ],
        ),
        migrations.RenameField(
            model_name='area',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='nome',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AddField(
            model_name='project',
            name='project_participants',
            field=models.ManyToManyField(related_name='project_participants', to='portfolio.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_teachers',
            field=models.ManyToManyField(related_name='class_teachers', to='portfolio.teacher'),
        ),
        migrations.AddField(
            model_name='author',
            name='areas',
            field=models.ManyToManyField(related_name='authors', to='portfolio.area'),
        ),
        migrations.AddField(
            model_name='article',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='portfolio.area'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='portfolio.author'),
        ),
        migrations.AddField(
            model_name='academiccourse',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='portfolio.class'),
        ),
    ]
