# Generated by Django 4.2.1 on 2023-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_tech_backend_tech_frontend_tech_other_delete_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercourse',
            name='course',
            field=models.CharField(max_length=70),
        ),
    ]
