# Generated by Django 4.2.1 on 2023-06-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_othercourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
