# Generated by Django 4.2.1 on 2023-06-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_teacher_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
