# Generated by Django 4.2.1 on 2023-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_teacher_link_alter_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curricularunit',
            name='teachers',
        ),
        migrations.AddField(
            model_name='curricularunit',
            name='Aditional_teacher',
            field=models.ManyToManyField(related_name='aditional_teachers', to='portfolio.teacher'),
        ),
        migrations.AddField(
            model_name='curricularunit',
            name='Responsible_teacher',
            field=models.ManyToManyField(related_name='responsible_teachers', to='portfolio.teacher'),
        ),
    ]
