# Generated by Django 4.2.1 on 2023-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_curricularunit_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curricularunit',
            name='Aditional_teacher',
        ),
        migrations.RemoveField(
            model_name='curricularunit',
            name='Responsible_teacher',
        ),
        migrations.AddField(
            model_name='curricularunit',
            name='teachers',
            field=models.ManyToManyField(related_name='teachers', to='portfolio.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
