# Generated by Django 4.2.1 on 2023-06-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_curricularunit_aditional_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curricularunit',
            name='teachers',
        ),
        migrations.AddField(
            model_name='curricularunit',
            name='additional_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_teachers', to='portfolio.teacher'),
        ),
        migrations.AddField(
            model_name='curricularunit',
            name='responsible_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_teachers', to='portfolio.teacher'),
        ),
    ]
