# Generated by Django 4.2.1 on 2023-06-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_curricularunit_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curricularunit',
            name='year',
            field=models.CharField(default='', max_length=5),
        ),
    ]
