# Generated by Django 4.2.1 on 2023-06-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_curricularunit_additional_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_participants',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
