# Generated by Django 4.2.1 on 2023-06-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_tech_other_author_alter_tech_other_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_backend',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tech_backend',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='tech_frontend',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tech_frontend',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
    ]
