# Generated by Django 4.2.1 on 2023-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_tech_backend_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_backend',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='tech_frontend',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='tech_other',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
    ]
