# Generated by Django 4.2.1 on 2023-06-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_subject_tech_backend_subject_tech_frontend_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_backend',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tech_frontend',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tech_other',
            name='subject',
        ),
    ]
