# Generated by Django 4.2.1 on 2023-06-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_subject_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Assunto',
        ),
    ]
