# Generated by Django 4.2.1 on 2023-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_rename_text_article_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='brief_description',
        ),
        migrations.AddField(
            model_name='article',
            name='description1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='url("../images/backiee-5769412.jpg")', upload_to='portfolio/static/portfolio/images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_title1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_title2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
