# Generated by Django 4.2.1 on 2023-06-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_rename_description_article_brief_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(choices=[('Business', 'Business'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Sports', 'Sports'), ('Other', 'Other')], default='Business', max_length=15),
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='portfolio.author'),
        ),
    ]
