# Generated by Django 4.2.1 on 2023-06-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_area_name_remove_article_author_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
