# Generated by Django 4.2.1 on 2023-06-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_remove_area_area_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.IntegerField(choices=[(1, 'Business'), (2, 'Technology'), (3, 'Entertainment'), (3, 'Lifestyle'), (4, 'Travel'), (5, 'Sports'), (6, 'Other')], default='Business'),
        ),
    ]
