# Generated by Django 4.2.1 on 2023-06-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_remove_article_area_remove_author_area_article_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description1',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
