# Generated by Django 4.2.1 on 2023-06-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='area',
        ),
    ]
